### ISSUE TITLE
英文标点符号后空格才能触发补全

### ISSUE THREAD

**Issue by harisonkhlil** [wlh320/rime-ls#10]
录了一个 Gif 图：

![CleanShot 2023-07-09 at 16 49 59](https://github.com/wlh320/rime-ls/assets/70578017/0b5bb4b9-2dd0-46d1-86ea-748a96c1b541)

对于 markdown 来说这不是致命的嘛，触发斜体，粗体等都非常麻烦。

**Comment by harisonkhlil** [comment]
还发现一个问题：

![CleanShot 2023-07-09 at 17 37 35](https://github.com/wlh320/rime-ls/assets/70578017/588e3bc8-674b-426e-a88e-91c5b12fb3e5)

这里可以在 [ 后面补全，但是补全把前面的 [ 补没了。

**Comment by wlh320** [comment]
我在我这试了一下，第一个问题在 vim + coc 的环境下可以稳定复现，在 nvim + 内置 lsp 的环境下没有这个问题。我猜测是由于不同的编辑器、lsp client、补全插件在各自实现补全功能的过程中触发自动补全的条件不同导致的。这个我在尝试测试vim之外的不同编辑器的过程中也发现过。可以先尝试根据你用的补全插件绑定一个快捷键手动触发补全临时解决下，我如果有时间会再详细检查下这个问题。

第二个问题在我这没有复现，这个应该是之前版本的问题，理论上已经解决了，不过不排除我测试不完善导致问题没有完全解决。你用的是最新的版本吗？

**Comment by harisonkhlil** [comment]
第二个其实原来会吧 [] 补全替换为 【你好]，后来不知道为啥会吧前一个 [ 补全掉变成 你好]

**Comment by wlh320** [comment]
由于 vim 和 rime 都是高度可配置的，说不定哪些配置碰到一起就会出问题，排查起来有一定难度。刚才我试了一下 lunar_pinyin 的配置确实会出现第二个问题，看来是 rime 配置对于特殊符号的处理不同导致的。

**Comment by wlh320** [comment]
一个新思路，还可以给 Rime 做一下配置，做一个适合 rime-ls 的输入方案。因为用户配置分离的，不会影响你的其他输入法。
以 markdown 为例，可以把不常输入但 markdown 需要的符号的改成上屏半角英文符号，用额外的方式输入中文标点符号。

**Comment by wlh320** [comment]
我又确认了一下，确实修改 rime 配置的 `ascii_punct` 强制输入西文标点可以避免因为有符号导致的不能补全吞字符的问题。上面说的自己写一个输入方案应该是可行的。要么标点符号直接上屏，要么强制西文标点，中文标点换一种输入方式。

**Comment by Kaiser-Yang** [comment]
你说的第二个问题，我也遇到了，关于中文输入我找到了比较好的解决方案：
1. 将输入方案中标点设置为西文输入。
2. 使用以下的代码通过标点+空格的方式在开启`rime-ls`的情况下输入中文，如果要输入英文，则是直接输入标点然后等一会儿（取决于`updatetime`的大小）

```lua
local punc_en = {',', '.', ':'}
local punc_zh = {'，', '。', '：'}
vim.api.nvim_create_autocmd('FileType', {
    pattern = rime_ls_filetypes,
    callback = function ()
        for _, mode in ipairs({'i', 's'}) do
            for i = 1, #punc_en do
                local src = punc_en[i] .. '<space>'
                local dst = 'rime_enabled ? "' .. punc_zh[i] .. '" : "' .. punc_en[i] .. ' "'
                vim.api.nvim_buf_set_keymap(0, mode, src, dst, {
                    noremap = true,
                    silent = false,
                    expr = true,
                })
            end
        end
    end
})
```

如果需要新的标点支持，只需要在`punc_en `中添加英文标点，在`punc_zh`中添加中文标点即可。
