### ISSUE TITLE
补全列表最多显示一页内容

### ISSUE THREAD

**Issue by MiuKaShi** [wlh320/rime-ls#11]
配置好后，发现只能显示一页的汉字补全内容，也就是说待选项最多9个。新bug？
![bug](https://tri-1251426408.cos.ap-tokyo.myqcloud.com/20230724235338083860.jpg)

**Comment by wlh320** [comment]
早期版本是按照 rime-ls 的配置取出足够的候选项返回。后面加入了翻页支持，就改为了遵循 rime 配置里面的配置的每页显示的候选个数，默认是通过 ,/./-/= 四个键来翻页，rime-ls 里的每页个数就废弃了。

你现在的 rime 配置里面是每页显示多少个呢

**Comment by MiuKaShi** [comment]
rime里配置了每页9个，刚改了下rime的翻页配置，试了下用-/=符号可以翻页了

**Comment by wlh320** [comment]
这个或许能通过修改编辑器的配置来实现，LSP server 这边只提供候选，应该是看不到编辑器里面的移动情况的
