### ISSUE TITLE
如何让`-`直接上屏

### ISSUE THREAD

**Issue by rainzm** [wlh320/rime-ls#13]
你好，我用的雾凇配置的小鹤双拼。

系统 Rime 和 rime-ls 共享一套配置。

在系统Rime里面，`-` 是直接上屏的，`+`是直接上屏的，`$`是直接作为`¥`上屏的。

但是在 rime-ls 里面，`+`和`$`都不会触发补全， 直接上屏，但是`-` 就会触发补全。

不知道是否可以配置？

**Comment by rainzm** [comment]
https://github.com/wlh320/rime-ls/assets/22927169/a22a01ce-90d3-4635-b341-575d04c1dd11

**Comment by rainzm** [comment]
https://github.com/wlh320/rime-ls/assets/22927169/b06b891e-37c4-4c16-b561-e53482467b08

**Comment by wlh320** [comment]
我猜测原因是因为我在
https://github.com/wlh320/rime-ls/blob/e5a060c5ea0b194a501859efd7193a4a899d1ba6/src/lsp.rs#L275
这里为了触发翻页硬编码了 LSP 的触发字符。

后面我可以考虑把这个改成可配置项，因为 - 确实在 markdown 里还挺常用的

**Comment by wlh320** [comment]
可以检查下最新的 commit，现在允许用户自定义触发字符。
我也是雾凇+小鹤双拼，我这里测试下面的配置可以避免这个问题了

```lua
-- 上面是其他配置
paging_characters = { ",", "." },
-- 下面是其他配置
```

**Comment by rainzm** [comment]
谢谢你，我试了一下，确实OK了。
不过像例子中设置`paging_characters = { ",", "." }`，在实际的使用中`,`和`.`并不能和预期一样完成翻页：


https://github.com/wlh320/rime-ls/assets/22927169/867caec1-a485-4e58-91eb-d82a62c31f44

**Comment by wlh320** [comment]
雾凇拼音默认是用 -/= 翻页的，rime-ls 这里的翻页配置要跟你在 rime 里的翻页配置保持一致

**Comment by rainzm** [comment]
明白了！

**Comment by rainzm** [comment]
@wlh320 发现一个现象，当我配置`paging_characters = { "=" }`，这样是为了实现`-`直接上屏，而且我只需要后翻页`=`。

这种情况下，单个`,`和`.` 无法触发补全，需要使用`tab`主动触发。为了让`,`和`.`和之前一样能够自动触发补全，我就配置了`paging_characters = { "=", ",", "." }`，这样是很好工作的。

所以我想这里的`paging_characters`的意思更像是 硬编码的触发补全的字符？至于是否能翻页是由 rime 本身配置决定的。

不知道这算不算一个问题，或者只是配置项的描述可以更好。

**Comment by wlh320** [comment]
是的，你的理解是对的，这个配置项可以当作是允许触发 LSP 补全的字符。

这样命名是因为 rime-ls 在设计上除了全局开启之外还支持另一种模式，仅在用户设定的某个特殊字符开头时才开启，我之前把这个也叫做触发字符。虽然都是触发，这个是为了触发 rime-ls 去输入，而后来加的配置项是为了触发 LSP 补全。

我想着这样容易产生混淆，就命名成现在的样子了，因为设置这个配置项的最大的用处还是为了配合 rime 用来翻页。
等下个版本我会在文档里面解释一下。
