### ISSUE TITLE
无法触发补全的场景

### ISSUE THREAD

**Issue by rainzm** [wlh320/rime-ls#14]
我遇到一个很奇怪的无法工作的场景，能够稳定复现。

https://github.com/wlh320/rime-ls/assets/22927169/1850c2de-dd23-44e0-a22c-aa7428c0ff0c

**Comment by wlh320** [comment]
是的，这个我也遇到过，但是触发条件没有试出来。最近会比较忙，等过段时间我有空的时候我会再详细检查一下。

**Comment by wlh320** [comment]
检查出来问题了，是我对用的 ropey 库的一个 as_str() 的接口的功能理解错了，导致了提前返回 null，使 LSP client 不再对后续内容做补全。我认为应该解决问题了，你再试试看
