### ISSUE TITLE
[Feature] 支持 c/s 模式

### ISSUE THREAD

**Issue by rainzm** [wlh320/rime-ls#15]
是否可以通过引入 server 模式，解决多开编辑器使用 rime-ls，数据库被锁的问题。

只有 server 模式下的 rime-ls 会访问数据库，其他的 rime-ls 访问 server。

**Comment by wlh320** [comment]
其实已经支持了，现在有一个 listen 参数，可以绑定一个本地的网络端口，让 LSP server 和 client 可以通过 TCP socket 进行通信，这样只需要开一个 rime-ls 实例，多开的编辑器都连接并通过这个实例做补全。我认为是能避免数据库上锁的问题的。
就是没怎么测试过，如果有需求你可以试一试，看看有没有什么问题。

注意传输的都是明文，不要发送流量到公网上面。

**Comment by rainzm** [comment]
client需要特殊配置嘛，我通过`rime_ls --listen 127.0.0.1:9257`手动起来一个rime-ls，然后启动两个nvim编辑文件，还会有输出日志显示数据库上锁的问题：
<img width="1523" alt="image" src="https://github.com/wlh320/rime-ls/assets/22927169/1eb50747-0a4b-4ec8-aadb-b5b660af48a7">

nvim的配置没有改。

**Comment by wlh320** [comment]
nvim 配置要改成通过网络连接，`cmd = vim.lsp.rpc.connect('127.0.0.1', 9257)`

**Comment by rainzm** [comment]
哇哦 你太棒了！终于可以用舒服的方式写文档了！
