### ISSUE TITLE
rime_ls启动了但是没有cmp的补全

### ISSUE THREAD

**Issue by EvaristeFan** [wlh320/rime-ls#2]
平台archlinux
neovim lspconfig+cmp

大佬，我第一次用rime，用的是添加了custom server
的那个方法，但是没有cmp的补全，是我配置的问题还是rime需要额外的配置呢

**Comment by wlh320** [comment]
对这个项目来说，一般 rime 不需要额外配置就能用，配置一下使用更舒服

目前项目的错误处理还不是很完善，你可以检查一下以下地方：
1. 配置示例里的用户目录有没有修改成你自己的
2. 配置示例默认是关闭状态，我一般要用的时候用快捷键手动开启
3. 第一次启动要等 rime 部署完才能用，有可能会慢一些，可以等一下再重新打开试试
4. 如果配置过 rime，看下是不是默认设置成英文模式了，这样也是不能用的
5. 运行 `:LspLog` 看看有没有什么错误输出
