### ISSUE TITLE
rime启动失败

### ISSUE THREAD

**Issue by MiuKaShi** [wlh320/rime-ls#22]
arch下之前一直正常, 最近发现无法自动完成rime的build了。使用的rime配置为[rime-ice](https://github.com/iDvel/rime-ice)
难道随着nvim或者lsp插件更新 无法用了 ?

**Comment by wlh320** [comment]
我也是 arch + rime-ice，用着挺正常的。rime 在 build 的时候有什么错误日志吗？

**Comment by MiuKaShi** [comment]
> 我也是 arch + rime-ice，用着挺正常的。rime 在 build 的时候有什么错误日志吗？

哪里查看，之前进入nvim后就会自动在user_data_dir里开始build，现在什么反应都没

**Comment by wlh320** [comment]
一般来说只有改了配置文件 rime 才会重新 build 吧？如果出错，日志应该会写在配置的 `log_dir` 里面

**Comment by MiuKaShi** [comment]
我全新配置了user_data_dir下的文件，照理启动nvim后应该自动build,但是 没有反应。log_dir 里也没有log日志.  
下面是rime_ls 配置

```
require("lspconfig").rime_ls.setup {
  -- cmd = vim.lsp.rpc.connect("127.0.0.1", 9257),
  filetypes = { "markdown.pandoc", "tex", "matlab" },
  init_options = {
    enabled = vim.g.rime_enabled,
    shared_data_dir = vim.fn.expand "/usr/share/rime-data", -- rime 公共目录
    user_data_dir = vim.fn.expand "~/.local/share/rime-ls", -- 指定用户目录, 最好新建一个
    log_dir = vim.fn.expand "~/.local/share/rime-ls/log", -- 日志目录
    trigger_characters = {}, -- 为空表示全局开启
    always_incomplete = false, -- [since v0.2.3] true 强制补全永远刷新整个列表，而不是使用过滤
    max_tokens = 0, -- [since v0.2.3] 大于 0 表示会在删除到这个字符个数的时候，重建所有候选词，而不使用删除字符操作
    preselect_first = true, --是否默认第一个候选项是选中状态，default false
    schema_trigger_character = "&", -- 当输入此字符串时请求补全会触发 “方案选单”
  },
  on_attach = rime_on_attach,
  capabilities = capabilities,
}

```

**Comment by wlh320** [comment]
第一次 build 时间会比较长，等待一会重新激活一下 rime_ls ？或者可以尝试用手动 `rime_deployer` 提前手动 build rime 配置

**Comment by MiuKaShi** [comment]
还是不行 使用了  rime_deployer --build <user_data_dir> 应该是成功build。 但是进入nvim后还是没反应。哪里可以看rime_ls 输出的错误log吗

**Comment by MiuKaShi** [comment]
这乌龙搞得，我的锅。rime_ls 的client 都没挂在buffer上。修正配置文件就好了。
