### ISSUE TITLE
rime 初始化的时候有日志输入影响lsp client的数据解析

### ISSUE THREAD

**Issue by sxhxliang** [wlh320/rime-ls#27]
rime 初始化的时候有日志输入影响client解析，导致无法正常解析lsp返回的数据，这个怎么解决呢？
比如
https://github.com/cmyr/lsp-client 
基于上面那个库的异步修改：
https://github.com/codestoryai/lsp_client

这两个库都无法直接调用rime-ls的

**Comment by wlh320** [comment]
#16 里有一段 javascript 写的 LSP client 代码，我记得是能正常连接的。可以参考下看看是哪里的问题？
