### ISSUE TITLE
如何配置不显示index？

### ISSUE THREAD

**Issue by cxwx** [wlh320/rime-ls#28]
<img width="318" alt="截屏2024-05-09 23 56 16" src="https://github.com/wlh320/rime-ls/assets/6235641/e00fe913-aede-4a7d-90ef-462aef07b8f7">

使用多个lsp，如何才能将中文前面的index去掉？同时使用多个lsp的场景

**Comment by wlh320** [comment]
现在还没法配置，你可以把这里改了再手动编译：

https://github.com/wlh320/rime-ls/blob/7b921e99cae0e95e118d2241e364eba1d702ae9d/src/lsp.rs#L226

**Comment by rainzm** [comment]
可以自定义cmp的排序

**Comment by cxwx** [comment]
> 可以自定义cmp的排序

主要我也不想把 中文放最前面，
cmp 目前还没有追加 index 显示功能，

姑且当一个feature request 把

**Comment by wlh320** [comment]
LSP server 返回的都是有序列表，所以不加 index 才是常态，因此刚才加上了不显示 index 的功能。但是为了强调通过数字选词的能力，还是打算默认显示，有需要自定义 label 的需求时再通过配置去掉。

**Comment by cxwx** [comment]
thanks
