### ISSUE TITLE
补全的都是繁体中文

### ISSUE THREAD

**Issue by 416207298** [wlh320/rime-ls#3]
如题，补全出来的是繁体，如何切换成简体呢？
![image](https://user-images.githubusercontent.com/19567041/222062394-40bfb98b-0331-4275-b8ef-7568d4e723a2.png)

**Comment by wlh320** [comment]
如果配置的 Rime 用户目录之前不存在，Rime 会使用默认配置，默认配置就是这样的，可以参考 Rime 的文档进行配置。

**Comment by 416207298** [comment]
在配置文件`~/.local/share/rime-ls/build/luna_pinyin.schema.yaml`中，`switches:`下的`- name: simplification`一行下方添加：`reset: 1`，即可打开繁简转换。

**Comment by wlh320** [comment]
按我理解， Rime 的设计不应该手动修改 build 目录下的内容，可以参考下[这个](https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E7%B0%A1%E5%8C%96%E5%AD%97%E8%BC%B8%E5%87%BA) 直接在用户目录下创建一个 luna_pinyin.custom.yaml 文件进行配置
