### ISSUE TITLE
不能正常切换到双拼输入

### ISSUE THREAD

**Issue by Kaiser-Yang** [wlh320/rime-ls#30]
我的操作如下：
```bash
sudo apt install ibus-rime
sudo apt install librime-data-double-pinyin
```
安装完成后，我已确认`usr/share/rime-data`下存在双拼方案:

![image](https://github.com/user-attachments/assets/fe1bd2e8-1b3a-47b0-ab43-d5704425cd8d)

然后我在`~/.config/ibus/rime/default.custom.yaml`中添加了方案：
![image](https://github.com/user-attachments/assets/caa44002-3bfa-4eaa-81e3-e952a362d436)

通过`ibus-daemon -rdx`重启`ibus`：
![image](https://github.com/user-attachments/assets/2779a625-557b-4892-8108-c22d0b812222)

打开文件进行方案选择，没有我想要选择的双拼方案：
![image](https://github.com/user-attachments/assets/b57c45fd-70e4-4a9e-b5d8-81e3e17f1a57)

另外我使用的`wsl`，不知道这个有影响吗？

**Comment by wlh320** [comment]
`rime_ls` 的 `user_data_dir` 跟 ibus 用的是一个吗？最好不要这样做，如果两个同时在用可能会导致数据库锁住不能输入。我推荐专门用一个目录来配置 `rime_ls`，配置的方式跟 ibus-rime 或者 fcitx-rime 没有显著差别。

**Comment by Kaiser-Yang** [comment]
> `rime_ls` 的 `user_data_dir` 跟 ibus 用的是一个吗？最好不要这样做，如果两个同时在用可能会导致数据库锁住不能输入。我推荐专门用一个目录来配置 `rime_ls`，配置的方式跟 ibus-rime 或者 fcitx-rime 没有显著差别。

不是同一个，是`user_data_dir = vim.fn.expand"~/.local/share/rime-ls"`，也就是说我需要创建这个文件夹，在里面放置`default.custom.yaml`等文件吗？

**Comment by Kaiser-Yang** [comment]
> > `rime_ls` 的 `user_data_dir` 跟 ibus 用的是一个吗？最好不要这样做，如果两个同时在用可能会导致数据库锁住不能输入。我推荐专门用一个目录来配置 `rime_ls`，配置的方式跟 ibus-rime 或者 fcitx-rime 没有显著差别。
> 
> 不是同一个，是`user_data_dir = vim.fn.expand"~/.local/share/rime-ls"`，也就是说我需要创建这个文件夹，在里面放置`default.custom.yaml`等文件吗？

我刚刚试了一下可以了，原来是这样配置的，我还以为是直接配置`rime`的文件， 谢谢你的帮助 @wlh320 。
