### ISSUE TITLE
使用最新的librime会编译失败

### ISSUE THREAD

**Issue by evpeople** [wlh320/rime-ls#35]
应该是由于上游librime库做了改动，librime-sys 生成的代码没有了一些方法

**Comment by wlh320** [comment]
有详细报错吗？感觉 librime 应该没怎么动 API ？

**Comment by wlh320** [comment]
在 windows 上尝试了一下确实 librime 的 nightly build，确实存在找不到一些 API 的问题

**Comment by evpeople** [comment]
我感觉是librime-sys使用的最新的 .h， 上游这次改动用了src/rime_api_deprecated.h 保持兼容性，但是因为中间经过了一次librime-sys的转换，所以产生了报错

**Comment by wlh320** [comment]
对，应该是这个原因。说不定 librime 后续哪个版本就会去掉 rime_api_deprecated.h 里的老 API，我找个时间迁移到新的比较保险，而且现在的 API 说新也不算新了，旧版本 librime 感觉也不会不支持。

**Comment by wlh320** [comment]
改成新 Rime API （已经是十多年前就有了）之后感觉没问题了，编译出来新老动态库应该都能用

**Comment by wlh320** [comment]
先 close 了，有问题再开
