### ISSUE TITLE
混输情况下，在insert 模式下光标一直显示当前输入法（“中”，“英”）是否更加方便？

### ISSUE THREAD

**Issue by RaidOpe** [wlh320/rime-ls#37]
这样可以辅助分辨 normal 模式，目光集中在文本，手动切换会比养成混输格式空格触发切换更灵活些。现在都有格式检查脚本去处理出版格式

**Comment by wlh320** [comment]
这应该需要插件才能实现吧？这个项目主要还是关注 LSP Server 的实现，只提供候选项给编辑器。具体怎么处理这些候选项要看插件的实现。文档里给出的各个编辑器的配置仅供参考，实际用的时候可以根据个人情况加各种功能。

比如我自己现在就是完全当补全用，编辑器基本上什么配置都没有。
