### ISSUE TITLE
Offset-Encoding issue since Neovim v0.10.2

### ISSUE THREAD

**Issue by wlh320** [wlh320/rime-ls#38]
升级至 Neovim v0.10.2 后，经常出现不能触发补全的情况，降级后一切正常。同时其他编辑器没有问题。

由于该现象非常类似客户端与服务端之间 UTF-8 和 UTF-16 编码协商错误，猜测可能与 Offset-Encoding 有关。暂未搞清楚具体是哪个 commit 导致的。有空 debug 一下

**Comment by wlh320** [comment]
我初步判断是 neovim 的一个重构 commit 想要将添加处理超过本行长度的 index，判断的实现有点问题。因为我看到后续他们还会再次重构相关功能，短时间内可能一直存在这个问题了。我直接退回上个版本用了。

**Comment by MiuKaShi** [comment]
我就说怎么最近没有发补全了，那先降级用用

**Comment by wlh320** [comment]
嗯，相关功能在上个月底已经修好了，下个版本应该就没啥问题了。降级麻烦的话，我是下载上个版本的 AppImage 临时用，也可以用最新的 nightly build。

**Comment by wlh320** [comment]
neovim v0.10.3 released, this issue is solved.

**Comment by wlh320** [comment]
`v0.10.3` 似乎还是有问题啊

**Comment by wlh320** [comment]
好吧，nightly build 是没问题的，但`str_utfindex`相关的重构 PR 似乎没有合进 v0.10.3，恐怕要等到 v0.11 才能正常用了。

**Comment by wlh320** [comment]
这个问题我在 #47 解决了。有错误的 neovim 版本也可以正常用了，但是需要在 neovim 配置 rime-ls 的时候设置 client capabilities，强制客户端只用 UTF-8 与服务端通信，像这样 `capabilities.general.positionEncodings = { 'utf-8' }`

**Comment by cxwx** [comment]
comment
如果和其他lsp混用 capabilities.general.positionEncodings = { 'utf-8' }
```
 multiple different client offset_encodings detected for buffer, this is not supported yet
 ```

**Comment by wlh320** [comment]
> comment 如果和其他lsp混用 capabilities.general.positionEncodings = { 'utf-8' }
> 
> ```
>  multiple different client offset_encodings detected for buffer, this is not supported yet
> ```

lspconfig 似乎还需要在 setup 时加一句  offset_encoding = "utf-8"
例如这样
https://github.com/wlh320/wlh-dotfiles/blob/85d41a30588642617177374b4cea2ec96c1b2740/config/nvim/init.lua#L457

我现在也没明白到底怎样是正确的配置方法，目前这样是没有 warning
