### ISSUE TITLE
如何实现顶字上屏

### ISSUE THREAD

**Issue by Kaiser-Yang** [wlh320/rime-ls#43]
在进行五笔输入的时候，可以在输入第五个字符的时候，自动上屏前四码的第一候选，请问这个如何实现？

**Comment by wlh320** [comment]
这个行为应该需要编辑器这边的插件配合。

现在输入第五个字符后的补全列表长什么样子？

**Comment by Kaiser-Yang** [comment]
> 这个行为应该需要编辑器这边的插件配合。
> 
> 现在输入第五个字符后的补全列表长什么样子？

![image](https://github.com/user-attachments/assets/fd72b62c-48bb-4baa-99fa-9a4dfada9228)

![image](https://github.com/user-attachments/assets/4d4e9217-ea95-4108-adbb-54afe87176b4)

**Comment by Kaiser-Yang** [comment]
> > 这个行为应该需要编辑器这边的插件配合。
> > 现在输入第五个字符后的补全列表长什么样子？
> 
> ![image](https://private-user-images.githubusercontent.com/58209855/395949087-fd72b62c-48bb-4baa-99fa-9a4dfada9228.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjA2MzQsIm5iZiI6MTczNDMyMDMzNCwicGF0aCI6Ii81ODIwOTg1NS8zOTU5NDkwODctZmQ3MmI2MmMtNDhiYi00YmFhLTk5ZmEtOWE0ZGZhZGE5MjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAzMzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ODRlYTk3Yjg4MjM0YWFiNzMyYTg2YTZiZmEyYzdmZGFlZjYyODBhZDMwMWU2OTRlZjZiNWY3Y2NlOWQwZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JlwG1ni93Oj-WEitir2DIM2X0jR9fiFNfEMgGUSQwuk)
> 
> ![image](https://private-user-images.githubusercontent.com/58209855/395949125-4d4e9217-ea95-4108-adbb-54afe87176b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjA2MzQsIm5iZiI6MTczNDMyMDMzNCwicGF0aCI6Ii81ODIwOTg1NS8zOTU5NDkxMjUtNGQ0ZTkyMTctZWE5NS00MTA4LWFkYmItNTRhZmU4NzE3NmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAzMzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MzczMmViM2NkMDA3Zjc4MTU0YTBiNmFhOWNhMzMxMGE1OTAwYjEyOGMzNTNjM2JhMzg2ODRkNTMyZDkxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OyeTLgg7DkuhNefmKToygcUybDIWTRCA_ny40kNLIT4)

期望效果：

![image](https://github.com/user-attachments/assets/d50f9928-2249-4d2d-a06e-f64abe4b0b9f)

**Comment by Kaiser-Yang** [comment]
这个功能在 `rime` 里面是通过下面的字段控制的：

![image](https://github.com/user-attachments/assets/700b0d56-512e-4c5d-b685-4b3ad91dc091)

**Comment by wlh320** [comment]
试了一下，按现在的逻辑，输入第五个字符后 `commit_text` 拿不到东西，和用数字选择后的行为不太一样。不知道是不是我 Rime 的 API 用得不对，等有时间再研究一下。

**Comment by Kaiser-Yang** [comment]
> 试了一下，按现在的逻辑，输入第五个字符后 `commit_text` 拿不到东西，和用数字选择后的行为不太一样。不知道是不是我 Rime 的 API 用得不对，等有时间再研究一下。

如果设置了 `max_code_length: 4`，输入五个字符确实应该拿不到东西。

**Comment by wlh320** [comment]
哦，不对，我搞错了， 我直接 clone 下来了你的配置没有改，原版的 `max_code_length` 没有设置为 4。我修改后在 `rime_api_console` 里测试了一下似乎是可以获取到的。

那么现在的问题就在于 rime-ls 的实现逻辑。目前是先尝试获取当前的候选列表，候选为空就尝试获取 commit.text ，不为空则返回。而模拟顶字上屏的话，会同时拥有 commit.text 和候选列表，如果都返回的话对其他输入方案有没有影响还得再测试一下。

即使客户端把 commit.text 返回了，用 LSP 的方式服务端也没法控制客户端让其直接上屏，还是得在客户端这边写插件配合。我初步考虑感觉服务端不用做什么，不如直接在插件侧写一些代码判断当前输入串的长度，在客户端把这个功能做了。

**Comment by Kaiser-Yang** [comment]
我想了一下，这个功能ls确实做不了。

等我空了在readme里加点nvim的配制并把一些有用的配制整理一下。
